### ISSUE TITLE
http://try.iotagency.sigfox.com reset password not working

### ISSUE THREAD

**Issue by ghost** [luisomoreau/sigfox-platform#10]
**Describe the bug**
The reset password functionality is not working.

**To Reproduce**
Try to reset a password via 'forgot password'

**Expected behavior**
The ability to reset the password for a user.

**Comment by adechassey** [comment]
Hello Giovanni,
In fact, this is not a bug but a functionality to activate.
I patched the "try" instance with the email service activated, it now works.
Thx,
Antoine
**(Please go to this repo next time: https://github.com/IoT-Makers/sigfox-platform)**
