### ISSUE TITLE
API key suddenly stopped working

### ISSUE THREAD

**Issue by ghost** [luisomoreau/sigfox-platform#11]
**Describe the bug**
We had a test running on https://try.iotagency.sigfox.com but it had stopped reporting on the 22nd of January. (The first message that got the 401 arrived at 2019-01-22 10:37:40)

On the SigFox backend we got a 401 message:

```
[ERROR] - Base station 3849 - 1 second
401 - Unauthorized - #1
POST https://api.try.iotagency.sigfox.com/api/Messages/sigfox HTTP/1.0
authorization : <was valid, redacted for obvious reasons>	
content-length : 180
accept-encoding : gzip,deflate
accept-language : fr
host : api.try.iotagency.sigfox.com
user-agent : SIGFOX
accept-charset : UTF-8;q=0.9,*;q=0.7
content-type : application/json

{ "deviceId": "20AEAB", "time": 1548682015, "seqNumber": 9, "data": "101207480000000100000001", "reception": [{ "id": "3849", "RSSI": -118.00, "SNR": 18.11 }], "duplicate": false }
```

The authorization key was however correct. 
I generated a new authorization key and inserted this one in the SigFox backend, and the 401 messages disappeared. The device is now reporting again.

**Expected behavior**
The key should have continued to work as it had already been running for a couple of days.

**Comment by ghost** [comment]
Moved it to the new repository (https://github.com/IoT-Makers/sigfox-platform) as previously requested.

**Comment by luisomoreau** [comment]
Thank you Giovanni.

I no longer work at Sigfox and the official repository has been moved to https://github.com/IoT-Makers/sigfox-platform as you commented.
Antoine or Siyu will come back to you soon about your issue https://github.com/IoT-Makers/sigfox-platform/issues/9.
Thank you for your report.
Best regards,
Louis
