### ISSUE TITLE
Mqtt Connector

### ISSUE THREAD

**Issue by kimoudev** [luisomoreau/sigfox-platform#6]
Please,  can you show how to use MQTT connector?

**Comment by adechassey** [comment]
Hi,

**FYI, the repo moved here:** https://github.com/IoT-Makers/sigfox-platform

_When adding an MQTT connector, you can create an alert on a device of your choice that will push data to this new connector._

**Step 1.** Create a connector with type "MQTT"
**Step 2.** Create an alert on a device with the MQTT connector created
**Step 3.** Trigger the alert and the message of your choice will be sent to this connector

Best,

Antoine

**Comment by kimoudev** [comment]
Hi @AntoinedeChassey 
I sent an email yesterday to this address in French `antoinedechassey@gmail.com`.
Could we continue the connversation in inbox please.

Thanks,
Joachim
