### ISSUE TITLE
HTTPS certificate of demoserver is expired

### ISSUE THREAD

**Issue by hollie** [luisomoreau/sigfox-platform#7]
**Describe the bug**

The HTTPS certificate on the demo server that is linked to in the documentation (https://sigfox-platform.thenorthweb.com/) has an expired HTTPS certificate. It results in the error NET::ERR_CERT_DATE_INVALID when you try to connect to it.

As a side note, and I'm not sure if this is a result of the failing HTTPS certificate, the callback from the Sigfox backend to the server returns a ```600 - Unresolved network address``` when we try to activate a callback to push data to the platform.

**To Reproduce**
1. Click on 'https://sigfox-platform.thenorthweb.com/'
2. See the error message

**Expected behavior**
I expect the site to load correctly.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Comment by luisomoreau** [comment]
Thank you!
I forgot to add an auto renewal.
It should be resolved by now.

**Comment by hollie** [comment]
Hey Luis,

thanks, kudos for your fast reply time! 

We're sending live data as we speak and I confirm the payloads now arrive, so that issue was also related to the certificate.

Best regards,
 Lieven.
