### ISSUE TITLE
Demo website down

### ISSUE THREAD

**Issue by ghost** [luisomoreau/sigfox-platform#8]
It seems that the Demo website is down. 

Kind regards,
Giovanni Vandewaetere.

![image](https://user-images.githubusercontent.com/11297050/50762776-45e74e00-126e-11e9-9cb1-39b0d93ec1a5.png)

**Comment by adechassey** [comment]
Hello Giovanni,
Please have a go here: [http://try.iotagency.sigfox.com](http://try.iotagency.sigfox.com)
Best regards,
Antoine

**Comment by ghost** [comment]
That one does work. Thanks!

Kind regards,
GIovanni.
