### ISSUE TITLE
Assigning users to an organisation

### ISSUE THREAD

**Issue by ghost** [luisomoreau/sigfox-platform#9]
**Describe the bug**
I am unable to assign other users to an organisation.
**To Reproduce**
Try adding users to an organisation.
**Expected behavior**
Possibility to add users to an organisation.

Kind regards,
Giovanni Vandewaetere.

**Comment by adechassey** [comment]
You must be admin for this operation. I put you admin.
You can now select a user when editing your organization (pencil icon on the header).
